### ISSUE TITLE
Develop a function to calculate land use change tables (crosstab) by planning units

### ISSUE THREAD

**Issue by dindiarto** [icraf-indonesia/LUMENSR#5]
Hey @mariaadeliaw, I'm working on developing a function to calculate crosstab tables for land use change analysis in Kalimantan Barat. I need RTRW (Regional Spatial Plan) or Kabupaten (District) boundaries in order to enable the function to iteratively produce crosstabs for each land allocation.

Cheers

**Comment by mariaadeliaw** [comment]
I have uploaded the shapefile here https://github.com/mariaadeliaw/lumens_updates/tree/main/data/kalbar/admin. For now, the testing data will be saved in that private repository. For further development, I think simple dummy data should be created to be included in the package's example instead of using real provincial data.

**Comment by dindiarto** [comment]
done,see and test [7a1357f](https://github.com/icraf-indonesia/LUMENSR/commit/7a1357f7af2acab9de82241acb1d1da2878a23d7)
